### PR TITLE
Feat: Added slashcmd supports

### PR DESCRIPTION
**Pull request by Rajkumar-justcoder**
## Related Issue
- Issue No. #1 

## Changes you made :
- removed server.js
- added /cmd 
- modified package.json for npm and node . run
- installed glob package

## Check list :

- [x] I have followed code style of this project.
- [x] I have read the [**CONTRIBUTING**](https://github.com/1tsak/OSC-Bot/blob/master/CONTRIBUTING.md) document.
- [x] All the aspects mentioned in the issue are covered.
- [x] The website is properly working after my changes.
- [x] 🌟 ed the repo

### Type of change :

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Output Screenshots :

serverinfo
image

ping 
image

start
image

social
image

/ cmds 
image

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
@1tsak pls merge this pr

**Review by 1tsak — APPROVED** [review]
Okay, Great work👍🏻

**Comment by 1tsak** [comment]
pls make sure you star the repo

**Comment by Rajkumar-justcoder** [comment]
> pls make sure you star the repo

Yup done

**Comment by Rajkumar-justcoder** [comment]
> Okay, Great work👍🏻

Thanks you✌️

**Pull request merged**
